import { Field } from "./filter";

export interface RuleSet {
   rules: [Field, any][];
   combinations: [Field, any][][];
};

const ExcludedCompanies: [Field, any][] = [
   ["company", /(myGwork - LGBTQ\+ Business Community)/gmi],
   ["company", /(Varsity Tutors, a Nerdy Company)/gmi],
   ["company", /(Kraken Digital Asset Exchange)/gmi],
   ["company", /(Lumenalta \(formerly Clevertech\))/gmi],
   ["company", /(Veeva Systems)/gmi],
   ["company", /(Raas Infotek)/gmi],
   ["company", /(Actalent)/gmi],
   ["company", /(Lumenalta)/gmi],
   ["company", /(DataAnnotation)/gmi],
   ["company", /(Health Match BC)/gmi],
   ["company", /(Braintrust)/gmi],
   ["company", /(Rackspace Technology)/gmi],
   ["company", /(Refonte Learning)/gmi],
   ["company", /(Oeson Learning)/gmi],
   ["company", /(Talentify.io)/gmi],
   ["company", /(Myticas Consulting)/gmi],
   ["company", /(TEEMA)/gmi],
   ["company", /(micro1)/gmi],
   // ["company", /()/gmi],
   // ["company", /()/gmi],
   // ["company", /()/gmi],
   

   // temporary
   ["company", /(Chainalysis)/gmi],
   ["company", /(Mastercard)/gmi],
   ["company", /(CrowdStrike)/gmi],
   ["company", /(GitLab)/gmi],
   ["company", /(Stripe)/gmi],
   ["company", /(Coinbase)/gmi],
   ["company", /(Leonardo.Ai)/gmi],
   ["company", /(Outlier)/gmi],
   ["company", /(TikTok)/gmi],
   ["company", /(Affirm)/gmi],
   ["company", /(Elastic)/gmi],
   ["company", /(Babylist)/gmi],
   ["company", /(Canonical)/gmi],
   ["company", /(Chainlink Labs)/gmi],
   ["company", /(Affirm)/gmi],
   ["company", /(Agoda)/gmi],
   // ["company", /()/gmi],
   // ["company", /()/gmi],
];

const ExcludedRoles: [Field, any][] = [
   ["name", /(Data Engineer)/gmi],
   ["name", /(Site Reliability Engineer)/gmi],
   ["name", /(Lead Data Engineer)/gmi],
   ["name", /(Lead QA Engineer)/gmi],
   ["name", /(Power BI Developer)/gmi],
   ["name", /(Staff Backend Engineer)/gmi],
   ["name", /(Data Scientist)/gmi],
   ["name", /(Machine Learning Engineer)/gmi],
   ["name", /(Senior QA Engineer)/gmi],
   ["name", /(Engineer Co-Op)/gmi],
   ["name", /(Principal Software Engineer)/gmi],
   ["name", /(Technical Lead)/gmi],
   ["name", /(Technical Lead)/gmi],
   ["name", /(Staff Software Engineer)/gmi],
   ["name", /(Raw Materials Assistant Developer)/gmi],
   ["name", /(ML Engineer)/gmi],
   ["name", /(Cloud Infrastructure Engineer)/gmi],
   ["name", /(Cloud Infrastructure Engineer)/gmi],
   ["name", /(Staff Engineer)/gmi],
   ["name", /(Senior System Engineer)/gmi],
   ["name", /(Java developer)/gmi],
   ["name", /(Java Engineer)/gmi],
   ["name", /(Platform Engineer)/gmi],
   ["name", /(Infrastructure Engineer)/gmi],
   ["name", /(iOS Engineer)/gmi],
   ["name", /(iOS Developer)/gmi],
   ["name", /(Salesforce Developer)/gmi],
   ["name", /(Principal Engineer)/gmi],
   ["name", /(Staff Software Engineer)/gmi],
   ["name", /(Software Developer, Machine Learning)/gmi],
   ["name", /(Intern \(Summer 2025\))/gmi],
   ["name", /(Salesforce Architect)/gmi],
   ["name", /(Staff Software Developer)/gmi],
   ["name", /(Senior Dotnet Developer)/gmi],
   ["name", /(Magento Developer)/gmi],
   ["name", /(Technical Architect)/gmi],
   ["name", /(Senior Java Developer)/gmi],
   ["name", /(Senior Graphics Programmer)/gmi],
   ["name", /(Senior salesforce Developer)/gmi],
   ["name", /(Salesforce Solutions Engineer)/gmi],
   ["name", /(Staff Fullstack Engineer)/gmi],
   ["name", /(Program Manager)/gmi],
   ["name", /(Backend Developer - Python)/gmi],
   ["name", /(Cloud Security Engineer)/gmi],
   ["name", /(Principal Game Designer)/gmi],
   ["name", /(Cloud DevOps Engineer)/gmi],
   ["name", /(Cloud Automation Engineer)/gmi],
   ["name", /(Guidewire developer)/gmi],
   ["name", /(Senior Security Engineer)/gmi],
   ["name", /(Senior Android Engineer)/gmi],
   ["name", /(Mainframe Engineer)/gmi],
   ["name", /(Technical Artist)/gmi],
   ["name", /(Clinical Counselor)/gmi],
   ["name", /(Registered Nurse)/gmi],
   ["name", /(Mechanical Engineer)/gmi],
   ["name", /(Senior Gameplay Engineer)/gmi],
   ["name", /(Lead Gameplay Programmer)/gmi],
   ["name", /(Embedded Linux Consultant)/gmi],
   ["name", /(Lead Bazel Engineer)/gmi],
   ["name", /(Senior DevOps)/gmi],
   ["name", /(Java Software Engineer)/gmi],
   ["name", /(Lead Programmer)/gmi],
   ["name", /(Senior Systems Engineer)/gmi],
   ["name", /(Backend Developer - Python \/ Golang)/gmi],
   ["name", /(M365 Solution Architect)/gmi],
   ["name", /(ServiceNow Developer)/gmi],
   ["name", /(Rust Developer)/gmi],
   ["name", /(Zortech Solutions)/gmi],
   ["name", /(Co-op Software Engineer)/gmi],
   ["name", /(Machine Learning Researcher)/gmi],
   ["name", /(Field Services Engineer)/gmi],
   ["name", /(Statistical Programmer)/gmi],
   ["name", /(Senior C# Developer)/gmi],
   ["name", /(Co-op Student)/gmi],
   ["name", /(Engineering Team Lead)/gmi],
   ["name", /(Infrastructure Software Engineer)/gmi],
   ["name", /(Machine Learning Scientist)/gmi],
   ["name", /(Infrastructure Software Developer)/gmi],
   ["name", /(Développeur C#)/gmi],
   ["name", /(Data Science Intern)/gmi],
   ["name", /(C\+\+ Developer)/gmi],
   ["name", /(Electrical Engineer)/gmi],
   ["name", /(Java Microservices Developer)/gmi],
   ["name", /(Infrastructure Architect)/gmi],
   ["name", /(SAP iXp Intern)/gmi],
   ["name", /(Applied Scientist)/gmi],
   ["name", /(Lead Game Designer)/gmi],
   ["name", /(Senior Game Designer)/gmi],
   ["name", /(Service Now Architect)/gmi],
   ["name", /(Senior Solution Architect)/gmi],
   ["name", /(Guidewire Solution Architect)/gmi],
   ["name", /(Principal SAS Programmer)/gmi],
   ["name", /(MLOPS Engineer)/gmi],
   ["name", /(Penetration Tester)/gmi],
   ["name", /(Workday Integration Developer)/gmi],
   ["name", /(Data Architect)/gmi],
   ["name", /(Senior Android Developer)/gmi],
   ["name", /(Principal Architect)/gmi],
   ["name", /(Senior Compiler Engineer)/gmi],
   ["name", /(Rendering Software Engineer)/gmi],
   ["name", /(Firmware Engineer)/gmi],
   ["name", /(Staff Security Developer)/gmi],
   ["name", /(AMS Verification Engineer)/gmi],
   ["name", /(Principal Full Stack Developer)/gmi],
   ["name", /(Embedded Engineer)/gmi],
   ["name", /(ServiceNow Architect)/gmi],
   ["name", /(Senior Engineering Manager)/gmi],
   ["name", /(Snowflake Developer)/gmi],
   ["name", /(Lead DevOps Engineer)/gmi],
   ["name", /(Embedded Software Engineer)/gmi],
   ["name", /(ServiceNow Architect )/gmi],
   // ["name", /()/gmi],
 ];

const ExcludedCombinations: [Field, any][][] = [
   [
      ["name", /(Front End Associate)/gmi],
      ["company", /(The Home Depot Canada)/gmi],
      ["location", /(West Vancouver, BC)/gmi]
   ],
   [
      ["name", /(Senior Software Engineer)/gmi],
      ["company", /(DarkVision)/gmi],
      ["location", /(DVancouver, BC)/gmi]
   ],
   [
      ["name", /(Enterprise Architect)/gmi],
      ["company", /(TEEMA)/gmi],
      ["location", /(Vancouver, BC)/gmi]
   ],
   [
      ["name", /(Principal MLOPs Engineer \(Canada\))/gmi],
      ["company", /(Rackspace Technology)/gmi]
   ],
   [
      ["name", /(Tools Software Engineer)/gmi],
      ["company", /(Electronic Arts \(EA\))/gmi]
   ],
];

const ExcludedLocations: [Field, any][] = [
   ["location", /(Azeroth)/gmi],
];

export const RULES: RuleSet = {
   rules: [...ExcludedCompanies, ...ExcludedRoles, ...ExcludedLocations],
   combinations: ExcludedCombinations
};